version: "3.8"
services:
  mysql:
    platform: linux/x86_64
    container_name: mysqlDB
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ums_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - fullstack
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "8082:8080"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules
    stdin_open: true
    depends_on:
      - api
  api:
    build: ./backend
    container_name: backend_c
    ports:
      - "3010:3010"
    stdin_open: true
    depends_on:
      - mysql
    networks:
      - fullstack

volumes:
  mysql-volume:

networks:
  fullstack:
    driver: bridge
